language: scala
scala:
  - "2.10.4"
  - "2.11.1"
jdk:
  - oraclejdk7
  - openjdk7
install: mvn clean install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true
branches:
  only:
    - develop
